// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVxi-wYmG7R8TQMc-PXcpSdE-1YlRW9Rc',
    appId: '1:750332568734:web:1f6955b125bbeebc53078f',
    messagingSenderId: '750332568734',
    projectId: 'intentional-dating-app',
    authDomain: 'intentional-dating-app.firebaseapp.com',
    storageBucket: 'intentional-dating-app.appspot.com',
    measurementId: 'G-W4027R0RNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWKygmlRrzCrPYnEm7E4ud88J0qKvzjqA',
    appId: '1:750332568734:android:353cdfa53498a88653078f',
    messagingSenderId: '750332568734',
    projectId: 'intentional-dating-app',
    storageBucket: 'intentional-dating-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrfeJlHHzLVeeumk01yOH6FRwXkur0YNk',
    appId: '1:750332568734:ios:b4444367706b237453078f',
    messagingSenderId: '750332568734',
    projectId: 'intentional-dating-app',
    storageBucket: 'intentional-dating-app.appspot.com',
    iosBundleId: 'com.example.intentionalDemo01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrfeJlHHzLVeeumk01yOH6FRwXkur0YNk',
    appId: '1:750332568734:ios:b4444367706b237453078f',
    messagingSenderId: '750332568734',
    projectId: 'intentional-dating-app',
    storageBucket: 'intentional-dating-app.appspot.com',
    iosBundleId: 'com.example.intentionalDemo01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVxi-wYmG7R8TQMc-PXcpSdE-1YlRW9Rc',
    appId: '1:750332568734:web:fcf7e25238e550ed53078f',
    messagingSenderId: '750332568734',
    projectId: 'intentional-dating-app',
    authDomain: 'intentional-dating-app.firebaseapp.com',
    storageBucket: 'intentional-dating-app.appspot.com',
    measurementId: 'G-D0JSKS5NXT',
  );
}
